import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/Components/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           <div className="flex text-primary bg-darkbg2">
              {/* sidebar */}
              <SideBar />
              {/* content */}
              <div className="sm:w-[60%] w-full h-screen bg-black">{children}</div>
              {/* sheet */}
              <div className="sm:w-[300px] h-screen bg-slate-700"></div>
            </div>
        
      </body>
    </html>
  );
}
